<span style="color:blue">**Question 1.0.1**</span> In the next cell, assign the name `new_year` to the larger among the following two numbers:

1. the **absolute value** of $2^{5}-2^{11}-2^1-3 $, and 
2. $5 \times 13 \times 31 + 7$.

Try to use just one statement (one line of code). Be sure to check your work by executing the test cell afterward.

```
BEGIN QUESTION
name: q11
```

In [1]:
new_year = max((2**5-2**11-2-3),5*13*31+7) # SOLUTION
new_year

2022

<span style="color:blue">**Question 2.0.1**</span> The module `math` also provides the name `e` for the base of the natural logarithm, which is roughly 2.71. Compute $e^{\pi}-\pi$, giving it the name `near_twenty`.

*Remember: You can access `pi` from the `math` module as well!*

```
BEGIN QUESTION
name: q21
```

In [104]:
near_twenty = math.e ** math.pi - math.pi # SOLUTION
near_twenty

19.99909997918947

### 2.1. Accessing functions

In the question above, you accessed variables within the `math` module. 

**Modules** also define **functions**.  For example, `math` provides the name `sin` for the sine function.  Having imported `math` already, we can write `math.sin(3)` to compute the sine of 3.  (Note that this sine function considers its argument to be in [radians](https://en.wikipedia.org/wiki/Radian), not degrees.  180 degrees are equivalent to $\pi$ radians.)

<span style="color:blue">**Question 2.1.1.**</span> A $\frac{\pi}{4}$-radian (45-degree) angle forms a right triangle with equal base and height, pictured below.  If the hypotenuse (the radius of the circle in the picture) is 1, then the height is $\sin(\frac{\pi}{4})$.  Compute that value using `sin` and `pi` from the `math` module.  Give the result the name `sine_of_pi_over_four`, in the next cell.

<img src="http://mathworld.wolfram.com/images/eps-gif/TrigonometryAnglesPi4_1000.gif">

[Source](http://mathworld.wolfram.com/images/eps-gif/TrigonometryAnglesPi4_1000.gif)

```
BEGIN QUESTION
name: q211
```

In [106]:
sine_of_pi_over_four = math.sin(math.pi / 4) # SOLUTION
sine_of_pi_over_four

0.7071067811865475

Let's examine our table to see what data it contains.

<span style="color:blue">**Question 3.0.1.**</span> Use the method `show` to display the first 5 rows of `trees`. 

*Reminder:* The terms "method" and "function" are technically not the same thing, but for the purposes of this course, we will often use them interchangeably.

**Hint:** `tbl.show(3)` will show the first 3 rows of the table `tbl`. Additionally, make sure not to call `.show()` without an argument, as this will crash your kernel!


In [113]:
trees.show(5) # SOLUTION

Notice that some of the values in this table are missing, as denoted by "nan." This means either that the value is not available or not applicable. You'll also notice that the table has a large number of columns in it!

### `num_columns`

The table property `num_columns` returns the number of columns in a table. (A "property" is just a method that doesn't need to be called by adding parentheses.)

Example call: `<tbl>.num_columns`

<span style="color:blue">**Question 3.0.2**</span> Use `num_columns` to find the number of columns in our trees dataset.

Assign the number of columns to `num_trees_columns`.

```
BEGIN QUESTION
name: q32
```

In [114]:
num_trees_columns = trees.num_columns # SOLUTION
print("The table has", num_trees_columns, "columns in it!")

The table has 19 columns in it!


### `select`

Most of the columns are about location -- which neighbourhood, longitude and latitude etc.  If we're not interested in that information, it just makes the table difficult to read.  This comes up more than you might think, because people who collect and publish data may not know ahead of time what people will want to do with it.

In such situations, we can use the table method `select` to choose only the columns that we want in a particular table. It takes any number of arguments. Each should be the name of a column in the table. It returns a new table with only those columns in it. The columns are in the order *in which they were listed as arguments*.

For example, the value of `trees.select("SPECIES_BOTANICAL","DIAMETER_BREAST_HEIGHT")` is a table with only the type of tree and measurement.



<span style="color:blue">**Question 3.0.3**</span> Use `select` to create a table with only the common name, latitude, and longitude of each tree.  Call that new table `trees_locations`. (Use separate longitude and latitude columns)

*Hint:* Make sure to be exact when using column names with `select`; double-check capitalization!

```
BEGIN QUESTION
name: q33
```

In [117]:
trees_locations = trees.select("SPECIES_COMMON", "LATITUDE", "LONGITUDE")
trees_locations

SPECIES_COMMON | LATITUDE | LONGITUDE
Chokecherry    | 53.4825  | -113.638
Cherry, Amur   | 53.5388  | -113.43
Chokecherry    | 53.499   | -113.547
Chokecherry    | 53.5001  | -113.545
Chokecherry    | 53.4339  | -113.596
Chokecherry    | 53.5179  | -113.666
Chokecherry    | 53.4537  | -113.583
Chokecherry    | 53.5029  | -113.495
Cherry, Amur   | 53.4818  | -113.515
Chokecherry    | 53.502   | -113.494
... (10190 rows omitted)

### `drop`

`drop` serves the same purpose as `select`, but it takes away the columns that you provide rather than the ones that you don't provide. Like `select`, `drop` returns a new table.

<span style="color:blue">**Question 3.0.4**</span> Suppose you just didn't want the `ID` and `CULTIVAR` columns in `trees_markets`.  Create a table that's a copy of `trees_markets` but doesn't include those columns.  Call that table `trees_without_id`.

```
BEGIN QUESTION
name: q34
```

In [120]:
trees_without_id = trees.drop("ID", "CULTIVAR") # SOLUTION
trees_without_id

NEIGHBOURHOOD_NAME  | LOCATION_TYPE | SPECIES_BOTANICAL          | SPECIES_COMMON | GENUS  | SPECIES    | DIAMETER_BREAST_HEIGHT | CONDITION_PERCENT | PLANTED_DATE | OWNER | Bears Edible Fruit | Type of Edible Fruit | COUNT | LATITUDE | LONGITUDE | LOCATION                                  | Point Location
DONSDALE            | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 7                      | 65                | 2011-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4825  | -113.638  | (53.48251246041853, -113.63848287480505)  | POINT (-113.63848287480505 53.48251246041853)
TERRACE HEIGHTS     | Park          | Prunus maackii             | Cherry, Amur   | Prunus | maackii    | 15                     | 65                | 2014-06-01   | Parks | Yes                | Amur Chokecherry     | 1     | 53.5388  | -113.43   | (53.538760633518145, -113.42974993954729) | POINT (-113.42974993954729 53.538760633518145)
GRANDVIEW HEIGHTS   | Park          | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 9                      | 65                | 1990-01-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.499   | -113.547  | (53.49895158933218, -113.5468343040665)   | POINT (-113.5468343040665 53.49895158933218)
GRANDVIEW HEIGHTS   | Park          | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 10                     | 65                | 1990-01-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.5001  | -113.545  | (53.500149635135145, -113.54511365672442) | POINT (-113.54511365672442 53.500149635135145)
AMBLESIDE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 12                     | 65                | 2010-05-31   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4339  | -113.596  | (53.43389856014283, -113.59581920007685)  | POINT (-113.59581920007685 53.43389856014283)
POTTER GREENS       | Park          | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 20                     | 65                | 1989-12-31   | Parks | Yes                | Schubert Chokecherry | 1     | 53.5179  | -113.666  | (53.51791097023782, -113.66574694431588)  | POINT (-113.66574694431588 53.51791097023782)
TERWILLEGAR TOWNE   | Centre Median | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 20                     | 65                | 1989-12-31   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4537  | -113.583  | (53.453739369922275, -113.58263894232672) | POINT (-113.58263894232672 53.453739369922275)
STRATHCONA JUNCTION | Buffer        | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 19                     | 65                | 1990-01-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.5029  | -113.495  | (53.50290999848199, -113.49486609539743)  | POINT (-113.49486609539743 53.50290999848199)
RIDEAU PARK         | Buffer        | Prunus maackii             | Cherry, Amur   | Prunus | maackii    | 12                     | 65                | 2009-06-01   | Parks | Yes                | Amur Chokecherry     | 1     | 53.4818  | -113.515  | (53.48180389358648, -113.51534208041981)  | POINT (-113.51534208041981 53.48180389358648)
STRATHCONA JUNCTION | Buffer        | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | 14                     | 65                | 1990-01-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.502   | -113.494  | (53.50202548601264, -113.49442888620283)  | POINT (-113.49442888620283 53.50202548601264)
... (10190 rows omitted)

<span style="color:blue">**Question 3.0.6** Use `donsdale_trees` to create a table called `donsdale_boulevard` containing trees on boulevards in donsdale.
```
BEGIN QUESTION
name: q36
```

In [27]:
donsdale_boulevard = donsdale_trees.where('LOCATION_TYPE', are.equal_to("Boulevard")) # SOLUTION
donsdale_boulevard

ID     | NEIGHBOURHOOD_NAME | LOCATION_TYPE | SPECIES_BOTANICAL          | SPECIES_COMMON | GENUS  | SPECIES    | CULTIVAR | DIAMETER_BREAST_HEIGHT | CONDITION_PERCENT | PLANTED_DATE | OWNER | Bears Edible Fruit | Type of Edible Fruit | COUNT | LATITUDE | LONGITUDE | LOCATION                                  | Point Location
448432 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 7                      | 65                | 2011-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4825  | -113.638  | (53.48251246041853, -113.63848287480505)  | POINT (-113.63848287480505 53.48251246041853)
475547 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 15                     | 65                | 2003-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4842  | -113.638  | (53.48424674686466, -113.63847157414696)  | POINT (-113.63847157414696 53.48424674686466)
475285 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 10                     | 65                | 2006-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4842  | -113.638  | (53.48422707177881, -113.6380416203384)   | POINT (-113.6380416203384 53.48422707177881)
475284 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 11                     | 65                | 2006-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4841  | -113.638  | (53.484088071882155, -113.63804397262649) | POINT (-113.63804397262649 53.484088071882155)
475544 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 11                     | 65                | 2003-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4843  | -113.639  | (53.48427164895583, -113.63900788141247)  | POINT (-113.63900788141247 53.48427164895583)
475541 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 10                     | 65                | 2003-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4844  | -113.639  | (53.484350389271135, -113.63851227395783) | POINT (-113.63851227395783 53.484350389271135)
538678 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 12                     | 65                | 1990-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4833  | -113.638  | (53.483303435585036, -113.6380459435861)  | POINT (-113.6380459435861 53.483303435585036)
475543 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 10                     | 65                | 2003-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4843  | -113.639  | (53.48432355080478, -113.6386647803945)   | POINT (-113.6386647803945 53.48432355080478)
475275 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 12                     | 65                | 2006-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4842  | -113.638  | (53.48415548514016, -113.63786921133817)  | POINT (-113.63786921133817 53.48415548514016)
475270 | DONSDALE           | Boulevard     | Prunus virginiana Schubert | Chokecherry    | Prunus | virginiana | Schubert | 14                     | 65                | 2006-06-01   | Parks | Yes                | Schubert Chokecherry | 1     | 53.4837  | -113.638  | (53.4836636232035, -113.63787170680027)   | POINT (-113.63787170680027 53.4836636232035)
... (225 rows omitted)

<span style="color:blue">**Question 4.0.1**</span> Create a table of movies released between 2010 and 2016 (inclusive) with ratings above 8. The table should only contain the columns `Title` and `Rating`, **in that order**.

Assign the table to the name `above_eight`.

*Hint:* Think about the steps you need to take, and try to put them in an order that make sense. Feel free to create intermediate tables for each step, but please make sure you assign your final table the name `above_eight`!

```
BEGIN QUESTION
name: q41
```

In [31]:
above_eight = imdb.where('Year', are.between(2010, 2017)).where('Rating', are.above(8)).select('Title', 'Rating') # SOLUTION
above_eight

Title                    | Rating
Gone Girl                | 8.1
Warrior                  | 8.2
Intouchables             | 8.5
Shutter Island           | 8.1
12 Years a Slave         | 8.1
Inside Out (2015/I)      | 8.5
Jagten                   | 8.2
Toy Story 3              | 8.3
How to Train Your Dragon | 8.1
Interstellar             | 8.6
... (10 rows omitted)

<span style="color:blue">**Question 4.0.2**</span> Use `num_rows` (and arithmetic) to find the *proportion* of movies in the dataset that were released 1900-1999, and the *proportion* of movies in the dataset that were released in the year 2000 or later.

Assign `proportion_in_20th_century` to the proportion of movies in the dataset that were released 1900-1999, and `proportion_in_21st_century` to the proportion of movies in the dataset that were released in the year 2000 or later.

*Hint:* The *proportion* of movies released in the 1900's is the *number* of movies released in the 1900's, divided by the *total number* of movies.

```
BEGIN QUESTION
name: q42
```

In [35]:
num_movies_in_dataset = imdb.num_rows # SOLUTION
num_in_20th_century = imdb.where('Year', are.below(2000)).num_rows # SOLUTION
num_in_21st_century = imdb.where('Year', are.above_or_equal_to(2000)).num_rows # SOLUTION
proportion_in_20th_century = num_in_20th_century / num_movies_in_dataset # SOLUTION
proportion_in_21st_century = num_in_21st_century / num_movies_in_dataset # SOLUTION
print("Proportion in 20th century:", proportion_in_20th_century)
print("Proportion in 21st century:", proportion_in_21st_century)

Proportion in 20th century: 0.684
Proportion in 21st century: 0.316


<span style="color:blue">**Question 5.1.1.**</span> Make an array containing the numbers 0, 1, -1, $\pi$, and $e$, in that order.  Name it `interesting_numbers`.  

*Hint:* How did you get the values $\pi$ and $e$ earlier up in this lab?  You can refer to them in exactly the same way here.

```
BEGIN QUESTION
name: q511
```

In [39]:
interesting_numbers = make_array(0, 1, -1, math.pi, math.e) # SOLUTION
interesting_numbers

array([ 0.        ,  1.        , -1.        ,  3.14159265,  2.71828183])

<span style="color:blue">**Question 5.1.2.**</span> Make an array containing the five strings `"Hello"`, `","`, `" "`, `"world"`, and `"!"`.  (The third one is a single space inside quotes.)  Name it `hello_world_components`.

*Note:* If you evaluate `hello_world_components`, you'll notice some extra information in addition to its contents: `dtype='<U5'`.  That's just NumPy's extremely cryptic way of saying that the data types in the array are strings.

```
BEGIN QUESTION
name: q512
```

In [43]:
hello_world_components = make_array("Hello", ",", " ", "world", "!") # SOLUTION
hello_world_components

array(['Hello', ',', ' ', 'world', '!'], dtype='<U5')

<span style="color:blue">**Question 5.1.3.**</span> Import `numpy` as `np` and then use `np.arange` to create an array with the multiples of 99 from 0 up to (**and including**) 9999.  (So its elements are 0, 99, 198, 297, etc.)

```
BEGIN QUESTION
name: q513
```

In [49]:
import numpy as np 
multiples_of_99 = np.arange(0, 9999 + 99, 99) # SOLUTION
multiples_of_99

array([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990,
       1089, 1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079,
       2178, 2277, 2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168,
       3267, 3366, 3465, 3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257,
       4356, 4455, 4554, 4653, 4752, 4851, 4950, 5049, 5148, 5247, 5346,
       5445, 5544, 5643, 5742, 5841, 5940, 6039, 6138, 6237, 6336, 6435,
       6534, 6633, 6732, 6831, 6930, 7029, 7128, 7227, 7326, 7425, 7524,
       7623, 7722, 7821, 7920, 8019, 8118, 8217, 8316, 8415, 8514, 8613,
       8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405, 9504, 9603, 9702,
       9801, 9900, 9999])

### Temperature readings
There are multiple weather stations in Canada that measure surface temperatures at different sites around the country.  The hourly readings are [publicly available](https://climate.weather.gc.ca/historical_data/search_historic_data_e.html).

Suppose we download all the hourly data from the Edmonton Internation Airport station for the month of May 2021.  To analyze the data, we want to know when each reading was taken, but we find that the data don't include the timestamps of the readings (the time at which each one was taken).

However, we know the first reading was taken at the first instant of May 2021 (midnight on December 1st) and each subsequent reading was taken exactly 1 hour after the last.

**Question 5.1.4.** Create an array of the *time, in seconds, since the start of the month* at which each hourly reading was taken.  Name it `collection_times`.

*Hint 1:* There were 31 days in May, which is equivalent to ($31 \times 24$) hours or ($31 \times 24 \times 60 \times 60$) seconds.  So your array should have $31 \times 24$ elements in it.

*Hint 2:* The `len` function works on arrays, too!  If your `collection_times` isn't passing the tests, check its length and make sure it has $31 \times 24$ elements.

```
BEGIN QUESTION
name: q514
```

In [53]:
collection_times = np.arange(0, 31*24*60*60, 60*60) # SOLUTION
collection_times

array([      0,    3600,    7200,   10800,   14400,   18000,   21600,
         25200,   28800,   32400,   36000,   39600,   43200,   46800,
         50400,   54000,   57600,   61200,   64800,   68400,   72000,
         75600,   79200,   82800,   86400,   90000,   93600,   97200,
        100800,  104400,  108000,  111600,  115200,  118800,  122400,
        126000,  129600,  133200,  136800,  140400,  144000,  147600,
        151200,  154800,  158400,  162000,  165600,  169200,  172800,
        176400,  180000,  183600,  187200,  190800,  194400,  198000,
        201600,  205200,  208800,  212400,  216000,  219600,  223200,
        226800,  230400,  234000,  237600,  241200,  244800,  248400,
        252000,  255600,  259200,  262800,  266400,  270000,  273600,
        277200,  280800,  284400,  288000,  291600,  295200,  298800,
        302400,  306000,  309600,  313200,  316800,  320400,  324000,
        327600,  331200,  334800,  338400,  342000,  345600,  349200,
        352800,  356

<span style="color:blue">**Question 5.2.1.**</span> Set `population_1973` to the world population in 1973, by getting the appropriate element from `population_amounts` using `item`.

```
BEGIN QUESTION
name: q521
```

In [63]:
population_1973 = population_amounts.item(23) # SOLUTION
population_1973

3942096442

But this is tedious and doesn't really take advantage of the fact that we are using a computer.

Instead, NumPy provides its own version of `log10` that takes the logarithm of each element of an array.  It takes a single array of numbers as its argument.  It returns an array of the same length, where the first element of the result is the logarithm of the first element of the argument, and so on.

<span style="color:blue">**Question 5.3.1.**</span> Use `np.log10` to compute the logarithms of the world population in every year.  Give the result (an array of 66 numbers) the name `population_magnitudes`.  Your code should be very short.

```
BEGIN QUESTION
name: q531
```

In [66]:
population_magnitudes = np.log10(population_amounts) # SOLUTION
population_magnitudes

array([9.40783749, 9.4141273 , 9.42107263, 9.42846742, 9.43619893,
       9.44437257, 9.45259897, 9.46110062, 9.4695477 , 9.47722498,
       9.48330217, 9.48910971, 9.49694254, 9.50648175, 9.51603288,
       9.5251    , 9.53411218, 9.54286695, 9.55173218, 9.56076229,
       9.56968959, 9.57867667, 9.58732573, 9.59572724, 9.60385954,
       9.61162595, 9.61911264, 9.62655434, 9.63388293, 9.64137633,
       9.64849299, 9.6565208 , 9.66413091, 9.67170374, 9.67893421,
       9.68632006, 9.69377717, 9.70132621, 9.70880804, 9.7161236 ,
       9.72336995, 9.73010253, 9.73688521, 9.74337399, 9.74963446,
       9.75581413, 9.7618858 , 9.76774733, 9.77343633, 9.77902438,
       9.7845154 , 9.78994853, 9.7953249 , 9.80062024, 9.80588805,
       9.81110861, 9.81632507, 9.82150788, 9.82666101, 9.83175555,
       9.83672482, 9.84161319, 9.84648243, 9.85132122, 9.85604719,
       9.8607266 ])

<img src="array_multiplication.jpg">

<span style="color:blue">**Question 5.3.2.**</span> Suppose the total charge at a restaurant is the original bill plus the tip. If the tip is 20%, that means we can multiply the original bill by 1.2 to get the total charge.  Compute the total charge for each bill in `restaurant_bills`, and assign the resulting array to `total_charges`.

```
BEGIN QUESTION
name: q532
```

In [71]:
total_charges = 1.2 * restaurant_bills # SOLUTION
total_charges

array([24.144, 47.88 , 37.212])

<span style="color:blue">**Question 5.3.3.**</span> The array `more_restaurant_bills` contains 100,000 bills!  Compute the total charge for each one.  How is your code different?

```
BEGIN QUESTION
name: q533
```

In [73]:
more_restaurant_bills = Table.read_table("more_restaurant_bills.csv").column("Bill")
more_total_charges = 1.2 * more_restaurant_bills # SOLUTION
more_total_charges

array([20.244, 20.892, 12.216, ..., 19.308, 18.336, 35.664])

The function `sum` takes a single array of numbers as its argument.  It returns the sum of all the numbers in that array (so it returns a single number, not an array).

<span style="color:blue">**Question 5.3.4.**</span> What was the sum of all the bills in `more_restaurant_bills`, *including tips*?

```
BEGIN QUESTION
name: q534
```

In [76]:
sum_of_bills = sum(more_total_charges) # SOLUTION
sum_of_bills

1795730.0640000193

<span style="color:blue">**Question 5.3.5.**</span> The powers of 2 ($2^0 = 1$, $2^1 = 2$, $2^2 = 4$, etc) arise frequently in computer science.  (For example, you may have noticed that storage on smartphones or USB flash drives come in powers of 2, like 16 GB, 32 GB, or 64 GB.)  Use `np.arange` and the exponentiation operator `**` to compute the first 30 powers of 2, starting from `2^0`.

*Hint 1:* `np.arange(1, 2**30, 1)` creates an array with $2^{30}$ elements and **will crash your kernel**. That's a lot of elements!

*Hint 2:* Part of your solution will involve `np.arange`, but your array shouldn't have more than 30 elements.

```
BEGIN QUESTION
name: q535
```

In [78]:
powers_of_2 = 2 ** np.arange(30) # SOLUTION
powers_of_2

array([        1,         2,         4,         8,        16,        32,
              64,       128,       256,       512,      1024,      2048,
            4096,      8192,     16384,     32768,     65536,    131072,
          262144,    524288,   1048576,   2097152,   4194304,   8388608,
        16777216,  33554432,  67108864, 134217728, 268435456, 536870912])

Now the data is combined into a single table! It's much easier to parse this data. If you need to know what the population was in 1959, for example, you can tell from a single glance.

<span style="color:blue">**Question 6.0.1**</span> In the cell below, we've created 2 arrays. Using the steps above, assign `top_10_movies` to a table that has two columns called "Rating" and "Name", which hold `top_10_movie_ratings` and `top_10_movie_names` respectively.

```
BEGIN QUESTION
name: q61
```

In [82]:
top_10_movie_ratings = make_array(9.2, 9.2, 9., 8.9, 8.9, 8.9, 8.9, 8.9, 8.9, 8.8)
top_10_movie_names = make_array(
        'The Shawshank Redemption (1994)',
        'The Godfather (1972)',
        'The Godfather: Part II (1974)',
        'Pulp Fiction (1994)',
        "Schindler's List (1993)",
        'The Lord of the Rings: The Return of the King (2003)',
        '12 Angry Men (1957)',
        'The Dark Knight (2008)',
        'Il buono, il brutto, il cattivo (1966)',
        'The Lord of the Rings: The Fellowship of the Ring (2001)')

top_10_movies = Table().with_columns("Rating", top_10_movie_ratings, "Name", top_10_movie_names) # SOLUTION

# We've put this next line here 
# so your table will get printed out 
# when you run this cell.
top_10_movies

Rating | Name
9.2    | The Shawshank Redemption (1994)
9.2    | The Godfather (1972)
9      | The Godfather: Part II (1974)
8.9    | Pulp Fiction (1994)
8.9    | Schindler's List (1993)
8.9    | The Lord of the Rings: The Return of the King (2003)
8.9    | 12 Angry Men (1957)
8.9    | The Dark Knight (2008)
8.9    | Il buono, il brutto, il cattivo (1966)
8.8    | The Lord of the Rings: The Fellowship of the Ring (2001)

#### Loading a table from a file

In most cases, we aren't going to go through the trouble of typing in all the data manually. Instead, we load them in from an external source, like a data file. There are many formats for data files, but CSV ("comma-separated values") is the most common. 

`Table.read_table(...)` takes one argument (a path to a data file in string format) and returns a table.  

*Hint: You might be super familiar with this method from the demo video Intro to Tables!*

<span style="color:blue">**Question 6.0.2** Remember from earlier in the lab -- `imdb.csv` contains a table of information about the 250 highest-rated movies on IMDb.  Load it as a table called `imdb`. We've actually done this eariler in an above cell!

```
BEGIN QUESTION
name: q62
```

In [85]:
imdb = Table.read_table('imdb.csv') # SOLUTION
imdb

Votes  | Rating | Title                 | Year | Decade
88355  | 8.4    | M                     | 1931 | 1930
132823 | 8.3    | Singin' in the Rain   | 1952 | 1950
74178  | 8.3    | All About Eve         | 1950 | 1950
635139 | 8.6    | Léon                  | 1994 | 1990
145514 | 8.2    | The Elephant Man      | 1980 | 1980
425461 | 8.3    | Full Metal Jacket     | 1987 | 1980
441174 | 8.1    | Gone Girl             | 2014 | 2010
850601 | 8.3    | Batman Begins         | 2005 | 2000
37664  | 8.2    | Judgment at Nuremberg | 1961 | 1960
46987  | 8      | Relatos salvajes      | 2014 | 2010
... (240 rows omitted)

<span style="color:blue">**Question 7.0.1**</span> Check out the `population` table from section 2 of this lab.  Compute the year when the world population first went above 6 billion. Assign the year to `year_population_crossed_6_billion`.

```
BEGIN QUESTION
name: q71
```

In [92]:
year_population_crossed_6_billion = population.where('Population', are.above_or_equal_to(6*10**9)).column('Year').item(0) # SOLUTION
year_population_crossed_6_billion

1999

<span style="color:blue">**Question 7.0.2**</span> Find the average rating for movies released before the year 2000 and the average rating for movies released in the year 2000 or after for the movies in `imdb`.

*Hint*: Think of the steps you need to do (take the average, find the ratings, find movies released in 20th/21st centuries), and try to put them in an order that makes sense.

```
BEGIN QUESTION
name: q72
```

In [95]:
before_2000 = np.mean(imdb.where('Year', are.below(2000)).column('Rating')) # SOLUTION
after_or_in_2000 = np.mean(imdb.where('Year', are.above_or_equal_to(2000)).column('Rating')) # SOLUTION
print("Average before 2000 rating:", before_2000)
print("Average after or in 2000 rating:", after_or_in_2000)

Average before 2000 rating: 8.278362573099415
Average after or in 2000 rating: 8.237974683544303


<span style="color:blue">**Question 7.0.3**</span> Here's a challenge: Find the number of movies that came out in *even* years.

*Hint:* The operator `%` computes the remainder when dividing by a number.  So `5 % 2` is 1 and `6 % 2` is 0.  A number is even if the remainder is 0 when you divide by 2.

*Hint 2:* `%` can be used on arrays, operating elementwise like `+` or `*`.  So `make_array(5, 6, 7) % 2` is `array([1, 0, 1])`.

*Hint 3:* Create a column called "Year Remainder" that's the remainder when each movie's release year is divided by 2.  Make a copy of `imdb` that includes that column (`imdb.with_column(...)` returns a new table).  Then use `where` to find rows where that new column is equal to 0.  Then use `num_rows` to count the number of such rows.

*Note:* These steps can be chained in one single statement, or broken up across several lines with intermediate names assigned. You’re always welcome to break down problems however you wish!

```
BEGIN QUESTION
name: q73
```

In [98]:
num_even_year_movies = imdb.with_column("Year Remainder", imdb.column("Year") % 2).where("Year Remainder", are.equal_to(0)).num_rows # SOLUTION
num_even_year_movies

127